module.exports = [
    {
        namaperusahaan: 'Google.Inc',
        alamat: 'Jl.Kauman 1 Malang',
        deskripsi: 'Google.Inc adalah perusahaan search engine yang bergerak dibidang Lorem Ipsum Dolor Sit Amet Bla Bla Bla Bla Bla Bla\n\nSpesifikasi Yang Dibutuhkan:\nIman High Level\nSholat 40 Rakaat Sehari\nKhatam sebulan 3 Kali',
        rating: '10',
        like: '9',
        dislike: '0',
        gaji: '1500000',
        tipe: 'Full Time',
        posisi: 'Tukang Ice Breaking',
        penerbit: 'ibrahimsyah10',
        lamar_url: 'http://google.com/',
        photo_url: '05c02499b4669ab71add61d73cd494ae.png'
    },
    {
        namaperusahaan: 'Samsung',
        alamat: 'Jl.Kauman 2 Malang',
        deskripsi: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia urna at nisi finibus rutrum.\n\nSpesifikasi:\nJujur\nSetia\nPeka\nTAJIR',
        rating: '10',
        like: '9',
        dislike: '0',
        gaji: '0',
        tipe: 'Part Time',
        posisi: 'Ibu dari Anak Anak ku',
        penerbit: 'ibrahimsyah10',
        lamar_url: 'http://samsung.com/',
        photo_url: '7d898d70f606a2fb2879f8621963e31f.png'
    },
    {
        namaperusahaan: 'PT.Indomie',
        alamat: 'Jl.Kauman 3 Malang',
        deskripsi: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia urna at nisi finibus rutrum.\n\nSpesifikasi:\nJujur\nSetia\nPeka\nTAJIR',
        rating: '10',
        like: '9',
        dislike: '0',
        gaji: '10000',
        tipe: 'Full Time',
        posisi: 'Security Tester',
        penerbit: 'DeveloperTemanKOS',
        lamar_url: 'http://google.com/',
        photo_url: 'indomie.png'
    },
    {
        namaperusahaan: 'Apple.Inc',
        alamat: 'Kidul Pasar',
        deskripsi: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia urna at nisi finibus rutrum.\n\nSpesifikasi:\nJujur\nSetia\nPeka\nTAJIR',
        rating: '10',
        like: '9',
        dislike: '0',
        gaji: '999',
        tipe: 'Part Time',
        posisi: 'Penggigit Logo',
        penerbit: 'DeveloperTemanKOS',
        lamar_url: 'http://apple.com/',
        photo_url: 'apple.png'
    },
    {
        namaperusahaan: 'Warnet Geming',
        alamat: 'Jl.Kauman 10 Malang',
        deskripsi: 'Lorem Ipsum Dolor Sit Amet Bla Bla Bla Bla Bla Bla\n\nSpesifikasi Yang Dibutuhkan:\nIman High Level\nSholat 40 Rakaat Sehari\nKhatam sebulan 3 Kali',
        rating: '10',
        like: '9',
        dislike: '0',
        gaji: '10000',
        tipe: 'Full Time',
        posisi: 'Operator + Joki',
        penerbit: 'DeveloperTemanKOS',
        lamar_url: 'http://google.com/',
        photo_url: 'warnet.png'
    },
    {
        namaperusahaan: 'Razer',
        alamat: 'Jl.Kauman 6 Malang',
        deskripsi: 'Lorem Ipsum Dolor Sit Amet Bla Bla Bla Bla Bla Bla\n\nSpesifikasi Yang Dibutuhkan:\nIman High Level\nSholat 40 Rakaat Sehari\nKhatam sebulan 3 Kali',
        rating: '10',
        like: '9',
        dislike: '0',
        gaji: '999',
        tipe: 'Full Time',
        posisi: 'Penghibur',
        penerbit: 'fulan',
        lamar_url: 'http://razer.com/',
        photo_url: 'Razer.png'
    }
]